name: Bug Report
description: Something isn't working
title: "[Bug] "
labels:
  - bug
  - need-triage
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Priority High
        - Priority Middle
        - Priority Low
    validations:
      required: true

  - type: input
    id: steps
    attributes:
      label: 复现步骤
      placeholder: 简要描述如何重现问题
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 详细描述
      placeholder: 请详细描述你遇到的问题
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 日志信息
      placeholder: 如有错误日志，请贴在这里
